name: hather_app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  easy_localization: ^3.0.3
  iconsax_flutter: ^1.0.0
  either_dart: ^1.0.0
  get_it: ^7.6.7
  equatable: ^2.0.5
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

